### ISSUE TITLE
reload.lua: Reload when VOD of current live stream on twitch is ended.

### ISSUE THREAD

**Issue by ekeelore** [4e6/dotfiles#4]
For now you need to manually reload the stream to load the rest of it in the current moment, but sometimes you forget about it and playback is ending. I suggest solving this issue, and with avoiding the infinite loading, when stream is actually ended.

**Comment by 4e6** [comment]
Nice, good catch!

I fixed the issue and created dedicated [mpv-reload](https://github.com/4e6/mpv-reload) repository. Note that this feature is disabled by default and you need to enable it with 

```
reload_eof_enabled=yes
```

Closing this for now. Please open a separate issue in the new repository if you have any troubles with the patch.
